### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by antoniodesa** [romanzipp/Laravel-SEO#31]
Hi,
would it be support for php8?
On composer update i get the following:
"romanzipp/laravel-seo[2.1.0, ..., 2.1.5] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement"

**Comment by romanzipp** [comment]
I've added PHP 8 support in version [2.1.8](https://github.com/romanzipp/Laravel-SEO/releases/tag/2.1.7)
