### ISSUE TITLE
Canonical Link

### ISSUE THREAD

**Issue by spekulatius** [romanzipp/Laravel-SEO#34]
**Describe the bug**

Hello @romanzipp 

I've used the shorthand for the canonical link and it added a `meta`-tag instead of the expected `link`-tag. I googled and couldn't find any information on a meta tag - only the typical `<link ... >`. Could this be a mistake? If so I'm happy to look into and provide a fix.

Cheers,
Peter

**Comment by romanzipp** [comment]
Right, I've opened PR #35 regarding this issue. I've only deprecated the previous meta struct to prevent any compatibility issues

**Comment by spekulatius** [comment]
Hey @romanzipp 

ah, nice. Thanks for checking it out and fixing it.

Cheers,
Peter

**Comment by spekulatius** [comment]
Could you tag a patch version @romanzipp ?

**Comment by romanzipp** [comment]
[2.2.5](https://github.com/romanzipp/Laravel-SEO/releases/tag/2.2.5) should contain the latest changes

**Comment by spekulatius** [comment]
Awesome, thank you!
