### ISSUE TITLE
How to set <script> attributes such as async and defer?

### ISSUE THREAD

**Issue by spekulatius** [romanzipp/Laravel-SEO#36]
Hello @romanzipp 

I was wondering how one would set `async` or `defer` on Script. As far as I've seen it isn't possible at the moment. Is this correct? With `addAttribute` being protected I can't see a way to set it. Do I miss the obvious way here?

Cheers,
Peter

**Comment by romanzipp** [comment]
Indeed, the `setAttribute` method is in the protected scope. Although you should be able to use [`->attr('async')`](https://github.com/romanzipp/Laravel-SEO/blob/master/src/Structs/Struct.php#L266) which is just a fluent wrapper for `setAttribute`

**Comment by spekulatius** [comment]
Ah, good point, I wasn't aware of this one. Thank you for pointing me in the right direction!
