### ISSUE TITLE
Add an option to render HTML5 tags

### ISSUE THREAD

**Issue by jeffsmor** [romanzipp/Laravel-SEO#41]
Is possible to set an option to render HTML5 tags instead XHTML?

Example:

`<meta name="description" content="Laravel" />`

to

`<meta name="description" content="Laravel">`

**Comment by romanzipp** [comment]
I've implemented a new config option in #42 
Will this work for you?

**Comment by jeffsmor** [comment]
Yes, it's exacly what I was talking about...
Awesome, thank you...
