### ISSUE TITLE
Use with jigsaw: "A facade root has not been set."

### ISSUE THREAD

**Issue by spekulatius** [romanzipp/Laravel-SEO#43]
Hello @romanzipp,

I'm trying to get the package working with jigsaw. I've updated [this starter](https://github.com/spekulatius/jigsaw-clean-blog) and wanted to add Laravel SEO to it. I wonder if it's possible, below are steps to reproduce the issue:

**To Reproduce**
1. Go to clone starter repo: `git clone https://github.com/spekulatius/jigsaw-clean-blog`
2. `composer install && yarn`
3. Add Laravel SEO: `composer require romanzipp/laravel-seo`
4. Add PHP block to `master.blade.php`: `@php $seo = \romanzipp\Seo\Facades\Seo::make(); @endphp`
5. Run `yarn dev`
6. See error

I'm not sure if it's possible to make the package work with jigsaw, it might be desirable tho.

Thanks,
Peter

**Comment by romanzipp** [comment]
Yep, I'm getting errors all over the place.

**When accessing the Seo instance via Facade:**
```
A facade root has not been set.
```

This package has been made for Laravel so you needed to update all Laravel specific patterns and method calls like
- Add container patterns for singletons & dependency injection (+ replace `app`-helper)
- Update config management

I haven't tried running any Laravel package with another framework

**Using the SeoService::make() static constructor:**
```
Call to undefined function romanzipp\Seo\Services\app()
```

You could try adding an autoload entry to your composer.json pointing to the `vendor/laravel/illuminate/Support/helpers.php` (or sth like that) file

**Comment by spekulatius** [comment]
Yeah, understandable. I just wondered if there is any way to get it working I've missed... Thanks for checking @romanzipp
