### ISSUE TITLE
Laravel Octane and tag duplication

### ISSUE THREAD

**Issue by cindreta** [romanzipp/Laravel-SEO#47]
**Describe the bug**
When using the plugin with Laravel Octane tags are duplicated. First off the title tag gets duplicated then anything added to the AddSeoDefaults middleware. I followed your tutorial(https://romanzipp.github.io/Laravel-SEO/example-app.html) on setting everything up including Providers and Middleware .

**To Reproduce**
1. Install the plugin and set everything as defined here: https://romanzipp.github.io/Laravel-SEO/example-app.html
2. Install Laravel Octane (https://github.com/laravel/octane)
3. Run app and see problems

**Expected behavior**
The tags should not be duplicated. 

**Screenshots**
https://i.postimg.cc/WbZhkY6j/Screenshot-2022-09-21-at-13-12-26.png

**Additional context**
I think this happens because Octane keeps requests in memory so somehow the plugin should reset the added metadata.

**Comment by romanzipp** [comment]
Honestly I haven't ever used Octane and I'm not planning on doing so. Could you try calling the [`clearStructs()`](https://github.com/romanzipp/Laravel-SEO/blob/master/src/Services/SeoService.php#L159) in your AppServiceProvider or somewhere else before adding additional tags?

**Comment by binaryfire** [comment]
Hi. Just wondering if this is still an issue?

**Comment by romanzipp** [comment]
You could try it out, as I said I'm nit using Octane. Clearing the structs should resolve this issue but feel free to submit an implementation
